# Generated by Django 3.1.7 on 2021-09-23 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hwtgenml.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('estimated_time', models.CharField(max_length=250)),
                ('is_new', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('file_path', models.ImageField(upload_to=hwtgenml.models.upload_to)),
                ('collection', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hwtgenml.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default='', max_length=250)),
                ('vendor_shortname', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('collection_shortname', models.CharField(default='', max_length=50)),
                ('uuid', models.CharField(default='', max_length=100)),
                ('api_url', models.CharField(default='', max_length=250)),
                ('num_items', models.IntegerField(default=0)),
                ('collection_downloaded', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwtgenml.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw', models.FileField(upload_to='UserModels')),
                ('sol', models.FileField(upload_to='UserModels')),
                ('lf', models.FileField(upload_to='UserModels')),
                ('estimated_time', models.CharField(editable=False, max_length=250)),
                ('is_open', models.BooleanField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('now_collection', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_model', to='hwtgenml.collection')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_text', models.TextField()),
                ('image', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='collection_texts', to='hwtgenml.collectionimage')),
            ],
        ),
        migrations.CreateModel(
            name='CaptionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognized_text', models.TextField()),
                ('confidence_level', models.IntegerField(default=0)),
                ('initial_text', models.TextField()),
                ('saved_text', models.TextField()),
                ('caption', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hwtgenml.caption')),
                ('image', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='hwtgenml.collectionimage')),
            ],
        ),
        migrations.AddField(
            model_name='caption',
            name='collection',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='hwtgenml.collection'),
        ),
        migrations.CreateModel(
            name='BoostrapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw', models.FileField(upload_to='BoostrapModels')),
                ('sol', models.FileField(upload_to='BoostrapModels')),
                ('lf', models.FileField(upload_to='BoostrapModels')),
                ('estimated_time', models.CharField(editable=False, max_length=250)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('now_collection', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_model', to='hwtgenml.collection')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
